Update update

diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,14 +1,14 @@
 #!/bin/bash
+# shellcheck disable=2060,2086,2046,2034
+
 [[ $(echo "$1" | tr '[:upper:]' '[:lower:]') == "offline" ]] && offline=true
 [[ $(echo "$1" | tr '[:upper:]' '[:lower:]') == "internal" ]] && internal=true
 
 
-cd /loginvsi
+cd /loginvsi || (echo "/loginvsi folder does not exist" && exit 1)
 if [ -d /loginvsi/hosting ]; then
     rm -rf /loginvsi/hosting
 fi 
-
-
 
 
 # Get the hosting repo
@@ -17,25 +17,17 @@ while read -r repo branch hostingfolder; do
         branch="master";
         hostingfolder="latest/Production/InternalDB"        
     else
-        branch="release";
+        branch="release"          
     fi 
-    if [ -z $offline ]; then 
-        if [ ! -z $internal ]; then
+    if [ -z "$offline" ]; then 
+        if [ -n "$internal" ]; then
             echo "Performing internal update from $2" 
-            git clone -q -b "$branch" "$2" /loginvsi/hosting;
+            git clone -q -b "$branch" "$2" /loginvsi/hosting || (echo "Failed to clone repository, made a typo perhaps?" && exit 1)                        
         else
-            curl -Lfs -m 10 https://github.com/LoginVSI/VirtualAppliance.git &> /dev/null
-            if [[ $? != 0 ]]; then 
-                echo "Failed to connect to github.com, make sure the appliance can access github.com"
-                exit
-            fi
-            curl -Lfs -m 10 https://hub.docker.com &> /dev/null
-            if [[ $? != 0 ]]; then 
-                echo "Failed to connect to hub.docker.com, make sure the appliance can access hub.docker.com"
-                exit
-            fi
+            curl -Lfs -m 10 https://github.com/LoginVSI/VirtualAppliance.git &> /dev/null || (echo "Failed to connect to github.com, make sure the appliance can access github.com" && exit 1)
+            curl -Lfs -m 10 https://hub.docker.com &> /dev/null || (echo "Failed to connect to hub.docker.com, make sure the appliance can access hub.docker.com" && exit 1)                        
             echo "Performing online update from $repo" 
-            git clone -q -b "$branch" "$repo" /loginvsi/hosting;
+            git clone -q -b "$branch" "$repo" /loginvsi/hosting || (echo "Failed to clone hosting repository, make sure the appliance can access github" && exit 1)                        
         fi
     else
         # offline updater, copy hosting files from hosting folder on iso        
@@ -47,7 +39,22 @@ while read -r repo branch hostingfolder; do
 	fi 
     currentversion=$(grep "Version__Number" < /loginvsi/docker-compose.yml | cut -d':' -f2 | cut -d"'" -f2 | tail -1)    
     newversion=$(grep "Version__Number" < /loginvsi/hosting/$hostingfolder/docker-compose.yml | cut -d':' -f2 | cut -d"'" -f2 | tail -1)
-    echo "This appliance is going to be updated to the latest version. Please make sure you have a backup of the system and data before proceeding."
+    if [ $repo == "https://github.com/LoginVSI/HostingTAT.git" ]; then         
+        echo "This appliance is going to be updated to the latest version. Please make sure you have a backup of the system and data before proceeding."
+    else
+        echo "
+########################################
+#  This appliance is going to be updated from $currentversion to $newversion          
+#  Please make sure you have a backup of the system and data before proceeding             
+#  After the update has finished please remember to update your launchers                
+########################################
+#  IMPORTANT NOTICES 
+#    3.5 
+#    The logonscript has been changed and needs to be updated in your environment
+#    3.4 
+#    After the update initial boot might take longer due to database maintenance 
+########################################"    
+    fi
     read -rep "Are you sure you want to update from $currentversion to $newversion [y/N]: " PROCEED </dev/tty
     DEFAULT="n"
     PROCEED="${PROCEED:-${DEFAULT}}"
@@ -67,7 +74,7 @@ while read -r repo branch hostingfolder; do
         cp -f "/loginvsi/hosting/$hostingfolder/docker-compose.yml" /loginvsi
         # get the status of trusted/untrusted certs
         currentcertsetting=$(grep SystemConfiguration__AllowUntrustedCertificates < /loginvsi/docker-compose.yml | head -n1 | cut -d':' -f2 | cut -d '"' -f2)
-        if [ ! -z $currentcertsetting ]; then 
+        if [ -n "$currentcertsetting" ]; then 
             # persist status of trusted/untrusted certs
             if [ $currentcertsetting == "true" ]; then
                 sed -i 's,SystemConfiguration__AllowUntrustedCertificates: "false",SystemConfiguration__AllowUntrustedCertificates: "true",g' /loginvsi/docker-compose.yml
@@ -96,6 +103,23 @@ if [[ "${PROCEED}" == "y" ]]; then
     systemctl disable loginvsid &>> /loginvsi/update.log
     systemctl enable loginvsid &>> /loginvsi/update.log
 
+    read -r repo branch hostingfolder < /root/.hosting
+    if [ $repo == "https://github.com/LoginVSI/Hosting.git" ]; then
+        branch="release"
+    else
+        branch="master"
+    fi
+    # Relaunch the update process from the daemon as it will now have a different address (AT or PI specific)
+    echo ""
+    echo -n "Virtual Appliance scripts repo change detected, restarting the update..."         
+    echo $repo $branch $hostingfolder > /root/.hosting            
+    kill -PIPE $PPID &>/dev/null
+    loginvsid update recurse
+    exit    
+    echo "should not see this line"                       
+    
+    
+
     if [ ! -f /etc/docker/daemon.json ]; then
         cp -f update/daemon.json /etc/docker
     fi
@@ -107,10 +131,10 @@ if [[ "${PROCEED}" == "y" ]]; then
 
 
     # create new db folders if needed
-    for f in $(cat /loginvsi/docker-compose.yml | grep "{DB_ROOT}")
+    for f in $(grep "{DB_ROOT}" < /loginvsi/docker-compose.yml)
     do 
         folder=$(echo $f | cut -d"-" -f2 | cut -d"/" -f2 | cut -d":" -f1) 
-        if [ ! -z $folder ]; then
+        if [ -n "$folder" ]; then
             if [ ! -d /loginvsi/data/$folder ]; then        
                 mkdir /loginvsi/data/$folder; 
             fi
@@ -124,7 +148,7 @@ if [[ "${PROCEED}" == "y" ]]; then
     servicesstartlinenumber=$(grep -n "^services:" /loginvsi/docker-compose.yml | cut -d':' -f1)
     OLDIFS=$IFS
     IFS=$'\n'
-    for line in $(tail -n+$secretsstartlinenumber /loginvsi/docker-compose.yml | head -n $(($servicesstartlinenumber-$secretsstartlinenumber)) | grep "^ "); do
+    for line in $(tail -n+$secretsstartlinenumber /loginvsi/docker-compose.yml | head -n $servicesstartlinenumber-$secretsstartlinenumber| grep "^ "); do
         
         if [[ -z $(echo $line | cut -d':' -f2) ]]; then 
             composesecrets+=$(echo $line | cut -d':' -f1 | xargs)
@@ -156,7 +180,7 @@ if [[ "${PROCEED}" == "y" ]]; then
     if [ -z $offline ]; then 
         # pull the new images from dockerhub if we are online
         echo $(cat /root/.play) | base64 -d | docker login -u vsiplayaccount --password-stdin &>> /loginvsi/update.log
-        cd /loginvsi
+        cd /loginvsi || (echo "/loginvsi folder cannot be found" && exit 1)
         docker-compose pull --quiet &>>/loginvsi/update.log
         if [ $? != 0 ]; then 
             echo "Something went wrong during pulling of the images from docker hub, please verify this appliance can connect to hub.docker.com"
